import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }



export const metadata = {
  title: "Rabby Portfolio",
  description: "Frontend Developer Portfolio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        
        
        
       <div className="flex items-center justify-between p-4 border-b border-gray-700">


      <div>
        <h1 className="text-4xl font-bold p-4">Rezae Rabby</h1>
      </div>
      <div>
        <nav className="flex justify-end p-4">
          <Link href="/" className="mx-4 hover:text-gray-400 bg-amber-300 p-3 rounded-lg">
            Home
          </Link>
          <Link href="/about" className="mx-4 hover:text-gray-400 bg-amber-300 p-3 rounded-lg">
            About
          </Link>
          <Link href="/skills" className="mx-4 hover:text-gray-400 bg-amber-300 p-3 rounded-lg">
            Skills
          </Link>
          <Link href="/contact" className="mx-4 hover:text-gray-400 bg-amber-300 p-3 rounded-lg">
            Contact
          </Link>
        </nav>
      </div>
    


        </div> 
        
        
        
        
        
        {children}</body>
    </html>
  );
}